version: "3.7"

services:

  db:
    image: postgres
    container_name: url_shortener_db
    restart: on-failure
    ports:
      - 5432:5432
    volumes:
      - ./sql:/docker-entrypoint-initdb.d:ro
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: PGPASSWORD='postgres' psql -U postgres --command='SELECT 1'
      interval: 10s
      timeout: 10s
      retries: 10
    networks:
      - urlshortenernet

  urlshortener:
    container_name: url_shortener_app
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - 8080:8080
    environment:
      DB_DSN: "postgres://postgres:postgres@db/postgres?sslmode=disable"
    volumes:
      - ./views:/app/views
    depends_on:
      db:
        condition: service_healthy
    networks:
      - urlshortenernet

networks:
  urlshortenernet: