openapi: 3.0.3
info:
  title: URL shortener service
  version: 1.0.0
tags:
- name: "Links"
  description: "Links"
paths:
  /links:
    post:
      tags:
      - "Links"
      summary: "Add a new link"
      operationId: "CreateLink"
      requestBody:
        description: "Link that needs to be added"
        content:
          text/plain:
            schema:
              type: string
        required: true
      responses:
        405:
          description: "Invalid input"
    get:
      tags:
      - "Links"
      summary: Links list with or without filters
      operationId: ListLinks
      parameters:
      - name: phrase
        in: query
        description: search phrase
        required: false
        schema:
          type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Link'
        404:
          description: Not found
          content: {}
  /links/{id}:
    delete:
      tags:
      - "Links"
      summary: Deletes a link
      operationId: DeleteLink
      parameters:
      - name: id
        in: path
        description: Link id to delete
        required: true
        schema:
          type: integer
          format: int64
      responses:
        400:
          description: Invalid ID supplied
          content: {}
        404:
          description: Item not found
          content: {}
components:
  schemas:
    Link:
      type: object
      properties:
        id:
          type: integer
          format: int64
        long:
          type: string
          format: url
        short:
          type: string
          format: url